//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2_QLSVLDA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINHVIENMONHOC
    {
        public string mssv { get; set; }
        public string mamonhoc { get; set; }
        public string kyhoc { get; set; }
        public Nullable<System.DateTime> thoigianbatdau { get; set; }
        public Nullable<System.DateTime> thoigianketthuc { get; set; }
        public string malop { get; set; }
    }
}
