//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2_QLSVLDA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINHVIENBAITAP
    {
        public string masinhvien { get; set; }
        public int mabaitap { get; set; }
        public string path { get; set; }
        public System.DateTime thoigiannop { get; set; }
        public string malop { get; set; }
        public string tenfile { get; set; }
        public string comment { get; set; }
    
        public virtual BAITAP BAITAP { get; set; }
    }
}
