//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2_QLSVLDA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINHVIEN
    {
        public string massv { get; set; }
        public string ten { get; set; }
        public System.DateTime namsinh { get; set; }
        public string sdt { get; set; }
        public string lop { get; set; }
        public short nien_khoa { get; set; }
        public string email { get; set; }
    }
}
