//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2_QLSVLDA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINHVIENCUOCHEN
    {
        public int macuochen { get; set; }
        public string masinhvien { get; set; }
        public string manhom { get; set; }
        public string magiaovien { get; set; }
        public Nullable<System.DateTime> thoigiandat { get; set; }
        public string malop { get; set; }
    
        public virtual CUOCHEN CUOCHEN { get; set; }
    }
}
